# Generated by Django 3.2.15 on 2022-08-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('discription', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
